services:
  - type: web
    name: schoolportal
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn your_project_name.wsgi"
    autoDeploy: true
