# Generated by Django 5.0.6 on 2024-07-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extracurricular', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
