# Generated by Django 5.0.6 on 2024-07-14 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_alter_student_admission_number_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='content',
        ),
        migrations.AddField(
            model_name='transcript',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_management.student'),
        ),
    ]
