# Generated by Django 5.0.6 on 2024-07-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0010_subject_transcript_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
